# 
# Do not Edit! Generated by:
# spec-builder version 0.13
# 

Name:       libdrm
Summary:    Direct Rendering Manager runtime library
Version:    2.4.4
Group:      System Environment/Libraries
License:    MIT
URL:        http://dri.sourceforge.net
Release:    1%{?dist}
Source0:  http://dri.freedesktop.org/libdrm/%{name}-%{version}.tar.bz2
Requires(post):  /sbin/service
Requires(post):  /sbin/chkconfig
Requires(postun): /sbin/service
Requires(postun): /sbin/chkconfig
BuildRequires:  pkgconfig(pthread-stubs)

BuildRoot:  %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

%description
Direct Rendering Manager runtime library


%package devel
Summary: Development files for %{name}
Group: Development/Libraries
Requires: %{name} = %{version}-%{version}
%description devel
Development files for %{name}



%prep
%setup -q -n %{name}-%{version}

%build
# >> build pre
# << build pre
%configure --disable-static

make %{?_smp_mflags}
# >> build post
# << build post

%install
# >> install pre
# << install pre
rm -rf %{buildroot}
%make_install

# >> install post
# << install post


%clean
rm -rf %{buildroot}
%post
/sbin/ldconfig

%postun
/sbin/ldconfig

%files 
%defattr(-,root,root,-)
# >> files 
/lib/blah.so.0.1
/etc/init.d/blah
# << files 

%files devel
%defattr(-,root,root,-)
# >> files devel
# << files devel
