# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.24.1
# 

Name:       spectacle

# >> macros
# << macros

%{!?python_sitelib: %define python_sitelib %(%{__python} -c "from distutils.sysconfig import get_python_lib; print get_python_lib()")}
Summary:    RPM Spec file generator and management tool
Version:    0.25
Release:    1
Group:      Development/Tools
License:    GPLv2+
BuildArch:  noarch
URL:        https://meego.gitorious.org/meego-developer-tools/spectacle
Source0:    spectacle-%{version}.tar.bz2
Source1:    autospectacle.pl
Source100:  spectacle.yaml
Requires:   python-yaml
Requires:   python-urlgrabber
Requires:   python-cheetah
Requires:   perl
BuildRequires:  python-devel
BuildRequires:  python-cheetah

%description
A tool for managing and creating RPM spec files



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
make tmpls
# << build pre

CFLAGS="$RPM_OPT_FLAGS" %{__python} setup.py build

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%{__python} setup.py install --root=%{buildroot} -O1

# >> install post
make install-data DESTDIR=${RPM_BUILD_ROOT}
install -m 0755 %{SOURCE1} ${RPM_BUILD_ROOT}%{_bindir}
# << install post


%files
%defattr(-,root,root,-)
# >> files
%doc README.md AUTHORS COPYING TODO
%doc examples/
%dir %{_datadir}/spectacle
%{_datadir}/spectacle/*
%{_bindir}/*
%{python_sitelib}/*
# << files
