--- /dev/null	2010-03-01 09:42:51.548118450 +0800
+++ output.spec	2010-03-16 18:06:45.000000000 +0800
@@ -0,0 +1,78 @@
+# 
+# Do not Edit! Generated by:
+# spectacle version 0.13
+# 
+# >> macros
+# << macros
+
+Name:       testpkg
+Summary:    Sample package for spectacle testings
+Version:    1.0
+Release:    1
+Group:      System/Base
+License:    BSD
+URL:        http://www.testpkg.org/
+Source0:    http://www.testpkg.org/testpkg-%{version}.tar.gz
+Source100:  testpkg.yaml
+
+%description
+Sample package for spectacle testings, which will be used as
+the base of all testings. In this YAML file, only basic keywords
+specified, plus with one sub package "devel".
+
+
+
+%package devel
+Summary:    Development files for %{name}
+Group:      Development/Libraries
+Requires:   %{name} = %{version}-%{release}
+
+%description devel
+This package contains development files for %{name}.
+
+
+%prep
+%setup -q -n %{name}-%{version}
+
+# >> setup
+# << setup
+
+%build
+# >> build pre
+# << build pre
+
+
+
+# >> build post
+# << build post
+%install
+rm -rf %{buildroot}
+# >> install pre
+# << install pre
+
+# >> install post
+# << install post
+
+
+
+%preun
+# >> preun
+# extra preun scripts 
+# for testing
+# << preun
+
+
+
+
+
+%files
+%defattr(-,root,root,-)
+# >> files
+# << files
+
+
+%files devel
+%defattr(-,root,root,-)
+# >> files devel
+# << files devel
+
